/**
 * Hand-curated Supabase Database type for b1n0.
 *
 * NOTE: This file is *not* generated by `supabase gen types typescript`.
 * That CLI requires a project-id + DB connection that lives outside
 * this repo, so we maintain this file by hand. When you add a new
 * column or RPC, update this file in the same PR — `npm run build`
 * will catch you if your code disagrees with the schema.
 *
 * Coverage goals:
 *   ▸ Every table the admin panels read or write.
 *   ▸ Every RPC called from the client.
 *   ▸ The shapes are accurate enough for `createClient<Database>()`
 *     to drive .from('x').select(...) and .rpc('y', {...}) typing.
 *
 * Keep it accurate, not exhaustive. Use `Json` for free-form fields.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// ── Row shapes ────────────────────────────────────────────────

export interface ProfileRow {
  id: string
  name: string | null
  username: string | null
  first_name: string | null
  last_name: string | null
  dob: string | null
  phone: string | null
  phone_country_code: string | null
  address_line1: string | null
  address_line2: string | null
  city: string | null
  state: string | null
  country: string | null
  balance: number
  tier: 1 | 2 | 3
  currency: string
  total_predictions: number
  correct_predictions: number
  total_cobrado: number
  role: string | null
  is_admin: boolean
  must_change_password: boolean
  avatar_url: string | null
  notification_prefs: Json | null
  created_at: string
}

export interface EventRow {
  id: string
  question: string
  category: string
  event_type: 'binary' | 'open'
  status: 'draft' | 'open' | 'closed' | 'resolved' | string
  created_at: string
  ends_at: string | null
  resolved_at: string | null
  resolved_outcome: string | null
  sponsor_amount: number | null
  platform_margin: number | null
  pool_size: number | null
  min_entry: number | null
  max_entry: number | null
  tier_required: 1 | 2 | 3 | null
}

export interface EventMarketRow {
  event_id: string
  pool_total: number
  pool_committed: number
  yes_shares: number
  no_shares: number
  spread_enabled: boolean
  status: 'open' | 'closed' | 'resolved' | string
  sponsor_amount: number | null
  platform_margin: number | null
  max_yes_liability: number
  max_no_liability: number
  lp_capital: number | null
  bet_pool: number | null
  fees_collected: number | null
  lp_return_pct: number | null
  updated_at: string
}

export interface PositionRow {
  id: string
  event_id: string
  user_id: string
  side: string
  contracts: number
  price_at_purchase: number
  payout_if_win: number
  fee_paid: number
  gross_amount: number
  status: 'active' | 'won' | 'lost' | 'sold' | string
  created_at: string
}

export interface PredictionRow {
  id: string
  user_id: string
  event_id: string
  side: string
  amount: number
  potential_cobro: number
  fee_paid: number | null
  status: 'active' | 'won' | 'lost' | 'sold' | string
  created_at: string
  resolved_at: string | null
}

export interface MarketTransactionRow {
  id: string
  position_id: string | null
  event_id: string
  user_id: string
  gross_amount: number
  fee_deducted: number
  net_to_pool: number
  spread_captured: number | null
  success: boolean
  tx_type: 'purchase' | 'sale' | string | null
  created_at: string
}

export interface BalanceLedgerRow {
  id: string
  user_id: string
  type: string
  amount: number
  balance_after: number
  label: string | null
  created_at: string
}

export interface PlatformConfigRow {
  key: string
  value: number | null
  value_text: string | null
  label: string | null
  updated_at: string
}

export interface PlatformLedgerRow {
  id: string
  event_id: string
  sponsor_amount: number | null
  platform_margin: number | null
  created_at: string
}

export interface RateLimitRow {
  id: string
  user_id: string
  action: string
  count: number
  window_start: string
  created_at: string
}

export interface LpDepositRow {
  id: string
  event_id: string
  user_id: string
  amount: number
  return_pct: number
  status: 'active' | 'returned' | 'partial_loss' | string
  fees_at_deposit: number | null
  payout: number | null
  created_at: string
}

export interface CommentRow {
  id: string
  event_id: string
  user_id: string
  parent_id: string | null
  body: string
  created_at: string
  updated_at: string
}

export interface NotificationRow {
  id: string
  user_id: string
  type: string
  title: string
  body: string | null
  read_at: string | null
  data: Json | null
  created_at: string
}

export interface FriendshipRow {
  id: string
  requester_id: string
  addressee_id: string
  status: 'pending' | 'accepted' | 'declined' | string
  created_at: string
}

// ── RPC shapes ────────────────────────────────────────────────

export interface CheckAdminStatusReturn {
  is_admin: boolean
  authenticated: boolean
  user_id?: string
  checked_at?: string
}

export interface AdminAdjustBalanceReturn {
  ok?: boolean
  error?: string
  new_balance?: number
}

export interface SweepToTreasuryReturn {
  ok?: boolean
  error?: string
  swept_total: number
  tx_count: number
}

export interface ExecutePurchaseReturn {
  position_id?: string
  contracts?: number
  price_at_purchase?: number
  payout_if_win?: number
  fee_paid?: number
  gross_amount?: number
  tx_fee_rate?: number
  yes_price_new?: number
  no_price_new?: number
  pool_remaining?: number
  error?: string
}

// ── Database — the shape Supabase expects ─────────────────────

type NoArgs = Record<string, never>

// Permissive insert/update shapes. Real defaults live in the DB schema;
// the supabase-js generic only needs *something* shaped like a record.
// Tighten per-table later if you want stricter inserts.
type InsertOptional = Record<string, unknown>
type UpdateOptional = Record<string, unknown>

type Table<Row extends object> = {
  Row: Row
  Insert: InsertOptional
  Update: UpdateOptional
  Relationships: []
}

export interface Database {
  public: {
    Tables: {
      profiles: Table<ProfileRow>
      events: Table<EventRow>
      event_markets: Table<EventMarketRow>
      positions: Table<PositionRow>
      predictions: Table<PredictionRow>
      market_transactions: Table<MarketTransactionRow>
      balance_ledger: Table<BalanceLedgerRow>
      platform_config: Table<PlatformConfigRow>
      platform_ledger: Table<PlatformLedgerRow>
      rate_limits: Table<RateLimitRow>
      lp_deposits: Table<LpDepositRow>
      comments: Table<CommentRow>
      notifications: Table<NotificationRow>
      friendships: Table<FriendshipRow>
    }
    Views: Record<string, never>
    Functions: {
      check_admin_status: {
        Args: NoArgs
        Returns: CheckAdminStatusReturn
      }
      is_admin: {
        Args: { user_id: string }
        Returns: boolean
      }
      admin_adjust_balance: {
        Args: { p_user_id: string; p_amount: number; p_reason?: string }
        Returns: AdminAdjustBalanceReturn
      }
      admin_reset_password: {
        Args: { p_user_id: string; p_new_password: string }
        Returns: { ok?: boolean; error?: string }
      }
      reset_user_password: {
        Args: { p_email: string }
        Returns: { ok?: boolean; temp?: string; error?: string }
      }
      sweep_to_treasury: {
        Args: NoArgs
        Returns: SweepToTreasuryReturn
      }
      update_platform_config: {
        Args: { p_key: string; p_value: number }
        Returns: void
      }
      settle_event: {
        Args: { p_event_id: string; p_result: string }
        Returns: Json
      }
      settle_predictions: {
        Args: { p_event_id: string; p_result: string }
        Returns: Json
      }
      initialize_market: {
        Args: {
          p_event_id: string
          p_pool_total?: number
          p_initial_yes_pct?: number
          p_spread_enabled?: boolean
          p_synthetic_shares?: number
          p_sponsor_amount?: number | null
          p_lp_return_pct?: number
          p_launch_mode?: string
        }
        Returns: EventMarketRow
      }
      initialize_option_markets: {
        Args: { p_event_id: string }
        Returns: Json
      }
      deposit_lp_capital: {
        Args: {
          p_event_id: string
          p_user_id: string
          p_amount: number
          p_return_pct?: number
        }
        Returns: Json
      }
      execute_purchase: {
        Args: { p_event_id: string; p_user_id: string; p_side: string; p_gross: number }
        Returns: ExecutePurchaseReturn
      }
      preview_purchase: {
        Args: { p_event_id: string; p_user_id: string; p_side: string; p_gross: number }
        Returns: Json
      }
      execute_sell: {
        Args: { p_position_id: string; p_user_id: string; p_contracts?: number }
        Returns: Json
      }
      execute_option_purchase: {
        Args: { p_event_id: string; p_user_id: string; p_option: string; p_gross: number }
        Returns: Json
      }
      preview_option_purchase: {
        Args: { p_event_id: string; p_user_id: string; p_option: string; p_gross: number }
        Returns: Json
      }
      cast_vote: {
        Args: { p_event_id: string; p_user_id: string; p_side: string; p_amount: number }
        Returns: Json
      }
      deposit_balance: {
        Args: { p_amount: number; p_label?: string }
        Returns: Json
      }
      withdraw_balance: {
        Args: { p_amount: number; p_method?: string }
        Returns: Json
      }
      check_rate_limit: {
        Args: { p_action: string; p_window_seconds?: number; p_max?: number }
        Returns: boolean
      }
      record_rate_limit: {
        Args: { p_action: string }
        Returns: void
      }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
